# Generated by Django 4.1 on 2022-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessels_in_Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(verbose_name='Run Date')),
                ('vessel_name', models.CharField(max_length=120, verbose_name='Vessel Name')),
                ('terminal', models.CharField(max_length=120, verbose_name='Terminal Name')),
            ],
        ),
    ]
