# Generated by Django 4.1 on 2022-09-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vessels_in_port',
            unique_together={('vessel_name', 'run_date')},
        ),
    ]
