# Generated by Django 4.1 on 2022-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_vessels_in_port_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessels_in_port',
            name='run_date',
            field=models.DateField(verbose_name='Run Date'),
        ),
    ]
